apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-depl
spec:
  selector:
    matchLabels:
      app: customer-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-pod
    spec:
      containers:
        - name: customer-pod
          image: "732631625641.dkr.ecr.us-east-2.amazonaws.com/ss-cloud-poc:customer-service-1.0"
          #image: "localhost:5000/ss-cloud-poc:customer-service-1.0"
          env:
          - name: ACCOUNT_SERVER_URL_BASE
            value: http://${SERVICE_ACCOUNT_SERVICE_HOST}:${SERVICE_ACCOUNT_SERVICE_PORT}
          # This container requires a derby database to be running
          - name: DERBY_DB_SERVER
            value: ${DERBY_DB_SERVICE_SERVICE_HOST}
          - name: DERBY_DB_PORT
            value: ${DERBY_DB_SERVICE_SERVICE_PORT}
          - name: DERBY_DB_USERNAME
            value: shibu
          - name: DERBY_DB_PASSWORD
            value: shibu
          ports:
            - name: acc-http-port
              containerPort: 8101
#      tolerations:
#      - key: "node.kubernetes.io/disk-pressure"
#        operator: "Exists"
#        effect: "NoExecute"

              
