apiVersion: apps/v1
kind: Deployment
metadata:
  name: derby-db-depl
spec:
  selector:
    matchLabels:
      app: derby-db-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: derby-db-pod
    spec:
      volumes:
      - name: vol
        hostPath:
          path: /dbs/
      containers:
        - name: derby-db-pod
          #image: "732631625641.dkr.ecr.us-east-2.amazonaws.com/ss-cloud-poc-container-repo:db-derby-1.0"
          image: "localhost:32000/local:db-derby-1.0"
          ports:
            - name: dbport
              containerPort: 1527
          volumeMounts:
          - name: vol
            mountPath: /dbs/
