apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-depl
spec:
  selector:
    matchLabels:
      app: loan-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: loan-pod
    spec:
      containers:
        - name: loan-pod
          image: "560773393352.dkr.ecr.us-east-2.amazonaws.com/ss-cloud-poc:loan-service-1.0"
          #image: "localhost:5000/ss-cloud-poc:loan-service-1.0"
          env:
          ports:
            - name: acc-http-port
              containerPort: 5000
#      tolerations:
#      - key: "node.kubernetes.io/disk-pressure"
#        operator: "Exists"
#        effect: "NoExecute"

              
